name: field_training_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

# versions available, run `flutter pub outdated`.
dependencies:
  awesome_dialog: ^3.2.0
  cached_network_image: ^3.3.1
  cherry_toast: ^1.10.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.1
  equatable: ^2.0.5
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  get_it: ^7.6.7
  google_fonts: ^6.1.0
  google_generative_ai: ^0.4.0
  google_nav_bar: ^5.0.6
  image_picker: ^1.0.7
  intl: ^0.19.0
  introduction_screen: ^3.1.14
  lottie: ^3.1.0
  open_file: ^3.3.2
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  syncfusion_flutter_pdfviewer: ^24.0.0
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animation/
    - assets/QB.pdf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
